### ISSUE TITLE
滑動關閉時機

### ISSUE THREAD

**Issue by raindy29** [tsx1453/slide_item#2]
打開按鈕後，如果通過拖拉欲關閉時，一定要拖到最右側才能動作
建議有一定的滑動比例時就能關閉，這樣比較順手

**Comment by tsx1453** [comment]
收到

**Comment by tsx1453** [comment]
已更新

**Comment by raindy29** [comment]
目前測試的結果，如果拖拉的並不是actionButoon區域，而是原本child內容，還是一定要拉到底才能收合，一般使用者習慣可能都以拉動child為主。
因為拉動actionButton可能會造成不小心觸發onTap

**Comment by tsx1453** [comment]
这个拖动是指手指拖动Item还没松开的过程吗，我自己也试过了，打开之后只需要拉到自己设置的阈值比例就能够直接关闭的，但是如果是处于正在打开的过程中不松手接着要关闭的确需要完全拉回去

**Comment by raindy29** [comment]
當已經完全展開actionButton後，使用者要關閉時，拖拉的區域不是ActionButton時，
要完全拖到底才能關閉。應該跟 拖拉 actionButton 區域一樣比例能關閉，這樣才會有比較好的體驗

**Comment by tsx1453** [comment]
https://ibb.co/kh8TPgc. 不知道是不是理解问题，我个人感觉好像没啥问题呀

**Comment by raindy29** [comment]
請你用滑鼠或手機在紫色區塊 "快速" 的滑動到右邊，其實是不會關閉的
但是在右邊的button即便是快速的滑動是會關閉的，一般使用者都是快速滑動去關閉
只有兩種方式才能關閉 
1.點擊紫色塊
2.慢慢的滑動
![Image 11](https://user-images.githubusercontent.com/10285124/80170117-cd9acc80-8619-11ea-9796-7b27ed12c320.png)

**Comment by tsx1453** [comment]
明白了，这个感觉是个人习惯问题吧，的确快速滑动没滑动到一定的距离的话有可能不会关闭，这个问题其实可以把 closeOpenedItemOnTouch 属性设置为true，这样触摸到Item就会执行关闭操作，然后关于快速滑动这个问题这里不能关闭是因为快速的滑动操作被认定成了手势的Cancel操作，如果对这方面有需求可以clone代码之后在 _SlideItemState类的_buildNormalSlideWidget方法中对onPanCalcel进行相关逻辑的实现以及处理即可

**Comment by raindy29** [comment]
我目前就是將 closeOpenedItemOnTouch = true
因为快速的滑动操作被认定成了手势的Cancel操作 >> 我不太理解你的意思
你這個套件就是透過actionbutton去確認，又跟滑動刪除混在一起談，對user而言是不夠友善
其實其他類似的套件這樣的操作都是可以的。

**Comment by tsx1453** [comment]
关于这一点每个人的需求都不一样，之前写这个只是因为 flutter_slidable 存在一些问题以及部分实现不太符合自身需求。关于Cancel操作是指快速滑动的情况没有按照正常的触摸事件的流程来走，从而导致了没有触发关闭的阈值；后面的透过actionbutton去确认不是很明白是什么意思，flutter端的另一个控件flutter_slidable刚刚下载了最新的代码运行的demo进行了测试其实也是存在快速滑动不会响应的问题的，这个功能主要看个人需求吧，代码都是开源的，如果自己有需求可以参考之后按照需求来进行开发，因为水平有限，之前做这个组件时对于滑动方向的判断并没有找到一个比较好用且准确的方案，所以对于一些比较细致方向判断可能没有进行处理，这个后续如果有比较好的方案会去尝试，最后还是感谢使用此控件
