### ISSUE TITLE
slideController.close() 無法動作

### ISSUE THREAD

**Issue by raindy29** [tsx1453/slide_item#4]
呼叫此事件時會產生錯誤 _slideController.close()

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'close' was called on null.
E/flutter ( 5037): Receiver: null
E/flutter ( 5037): Tried calling: close()

以下為程式碼，不曉得不是有什麼地方要注意的?
return SlideConfiguration(

      config: SlideConfig(
          slideOpenAnimDuration: Duration(milliseconds: 200),
          slideCloseAnimDuration: Duration(milliseconds: 400),
          deleteStep1AnimDuration: Duration(milliseconds: 250),
          deleteStep2AnimDuration: Duration(milliseconds: 300),
          supportElasticity: true,
          closeOpenedItemOnTouch: true,
          slideProportion: 0.2,
          actionOpenCloseThreshold: 0.3,
          backgroundColor: Colors.white),
      child: Padding(padding: const EdgeInsets.all(0.0), child: child),
      controller: _slideController,
    );

**Comment by tsx1453** [comment]
是不是_slideController只声明没有创建实例，_slideController.close内部调用的方法是_close，从错误信息来看好像是_slideController的空指针异常

**Comment by raindy29** [comment]
謝謝提醒，請關閉此問題
