### ISSUE TITLE
不同SlideItem的是否可以为设置不同的宽度

### ISSUE THREAD

**Issue by shawn736** [tsx1453/slide_item#6]
你好，不同的SlideItem是否可以设置为不同的宽度？比如第一个Item宽度是50，第二个是Item宽度是80。

**Comment by tsx1453** [comment]
已支持，抱歉好久没管这个了

**Comment by shawn736** [comment]
> 已支持，抱歉好久没管这个了

赞，这个功能很有用。虽然已经改用其他方法，还是要多谢分享和维护。
