### ISSUE TITLE
第1个SlideItem划开delete后，无法自动关闭

### ISSUE THREAD

**Issue by wangfeng110** [tsx1453/slide_item#7]
第1个SlideItem划开delete后，点击当前SlideItem会自动关闭，但是点击其他SlideItem或拖动ListView均不会自动关闭，其他SlideItem无此问题。

**Comment by tsx1453** [comment]
已修复～  >0 的判断写得有问题，应该是 >=0 ，demo刚好屏蔽了第一个Item，之前改了没发现。。。

**Comment by wangfeng110** [comment]
赞，多谢分享和维护。
